# Banana

In [9]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('MNSIT/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

MNSIT/american_sign_language.PNG
MNSIT/amer_sign2.png
MNSIT/amer_sign3.png
MNSIT/sign_mnist_test\sign_mnist_test.csv
MNSIT/sign_mnist_train\sign_mnist_train.csv

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

Using TensorFlow backend.

In [3]:
train_df = pd.read_csv("MNSIT/sign_mnist_train/sign_mnist_train.csv")
test_df = pd.read_csv("MNSIT/sign_mnist_test/sign_mnist_test.csv")

print('train data shape:', train_df.shape)
print('test data shape:', test_df.shape)

train data shape: (27455, 785)
test data shape: (7172, 785)

In [4]:
test = pd.read_csv("MNSIT/sign_mnist_test/sign_mnist_test.csv")
y = test['label']

print ('done')

done

In [5]:
train_df.head(5)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179

In [8]:
test_df.head(5)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,6,149,149,150,150,150,151,151,150,151,...,138,148,127,89,82,96,106,112,120,107
1,5,126,128,131,132,133,134,135,135,136,...,47,104,194,183,186,184,184,184,182,180
2,10,85,88,92,96,105,123,135,143,147,...,68,166,242,227,230,227,226,225,224,222
3,0,203,205,207,206,207,209,210,209,210,...,154,248,247,248,253,236,230,240,253,255
4,3,188,191,193,195,199,201,202,203,203,...,26,40,64,48,29,46,49,46,46,53